name: flutterflow_ui
description: UI components used by FlutterFlow's code generation.
homepage: https://docs.flutterflow.io
repository: https://github.com/FlutterFlow/flutterflow-ui

# google_mobile_ads, flutter_braintree, and chat have been disabled.
# flutter_html, sign_in_with_apple, and assets_audio_player have been added manually.



# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  chewie: 1.2.2
  collection: 1.17.1
  emoji_flag_converter: 1.1.0
  fl_chart: 0.50.6
  flutter_credit_card: 2.0.0
  flutter_google_places: 0.3.0
  font_awesome_flutter: 10.1.0
  google_api_headers:
  google_fonts: 2.2.0
  google_maps_flutter: 2.1.1
  google_maps_webservice:
  internet_file: 1.0.0+2
  intl: 0.17.0
  json_path: 0.3.1
  json_serializable: 6.1.3
  mapbox_search: 3.0.1+2
  mime_type: 1.0.0
  page_transition: 2.0.4
  pdfx: 2.0.1+2
  rive: 0.7.33
  rxdart: 0.26.0
  shared_preferences: 2.0.11
  table_calendar: 3.0.5
  timeago: 3.1.0
  url_launcher: 6.0.15
  video_player: 2.2.7
  webviewx: 0.2.2
  youtube_plyr_iframe: 2.0.7
  
  # For assets_audio_player
  uuid: ^3.0.5
  http: ^0.13.3 # to download / cache network files
  path_provider: ^2.0.8 # removed this because it cancel flutter/android/ios on pub.dev path_provider: ^1.6.10

  # For flutter_html
  html: '>=0.15.0 <1.0.0'
  csslib: '>=0.17.0 <1.0.0'
  flutter_layout_grid: '>=1.0.1 <2.0.0'
  webview_flutter: '>=2.0.4 <3.0.0'
  chewie_audio: '>=1.2.0 <2.0.0'
  flutter_svg: '>=0.22.0 <1.0.0'
  numerus: '>=1.1.1 <2.0.0'

dev_dependencies:
  dependency_validator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

